name = "whats-that-tech"
compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat_v2"]

pages_build_output_dir = "./public"

# Add browser binding back - seems required even for Pages Functions
browser = { binding = "MYBROWSER" }