name: Build and Commit Dist Files

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push if dist/ changed
        run: |
          git add -f dist/
          git restore pnpm-lock.yaml  # prevent accidental commit of unrelated changes

          if ! git diff --quiet || ! git diff --staged --quiet; then
            echo "🚀 Changes detected in dist/. Committing..."
            git commit -m "chore: update dist files [skip ci]"
            git push
          else
            echo "✅ No changes to dist/ — skipping commit"
          fi
